### Cadastro
POST http://localhost:3003/user/signup 
Content-Type: application/json

{
   "name":"Felipe", 
   "email":"felipe@gmail.com", 
   "password":"1234567", 
   "role":"ADMIN"
}


### Login
POST http://localhost:3003/user/login 
Content-Type: application/json

{
   "email": "felipe@gmail.com", 
   "password":"1234567"
}

###  Registrar banda
POST http://localhost:3003/band/add 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEwMTI1ZTdiLWRmNmItNGU3NC1iOWZkLTdmMDE5ODQyMzUxYyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2OTI5OTY2NSwiZXhwIjoxNjY5MzAwMjY1fQ.8NrfYa3oIBJN6UyM0NnyN5KH5TpvPi-z83ZLJbcsQWk
Content-Type: application/json

{
   "name": "Chá de casa nova", 
   "music_genre": "Sertanejo", 
   "responsible": "Henrique e Juliano"
}


### DETALHES DAS BANDAS
GET http://localhost:3003/band/details/28b90bd2-c9f9-4842-b80f-9868f3b0c358

###BUSCAR BANDA PELO DIA E ORDENAR
GET http://localhost:3003/band/details/search?domingo

### ADICIONAR LISTA DE SHOWS
POST http://localhost:3003/band/added/:bandId
Content-Type: application/json

{
    "weekDay" : "DOMINGO",
    "startTime" : 12,
    "endTime" : 13
}

