### Cadastro
POST http://localhost:3003/user/signUp 
Content-Type: application/json

{
   "name":"Elli", 
   "email":"elli@gmail.com", 
   "password":"12345678", 
   "role":"ADMIN"
}


### Login
POST http://localhost:3003/user/login 
Content-Type: application/json

{
   "email": "elli@gmail.com", 
   "password":"12345678"
}

###  Registrar banda
POST http://localhost:3003/band/add 
Authorization: token 
Content-Type: application/json

{
   "name": "Chá de casa nova", 
   "music_genre": "Sertanejo", 
   "responsible": "Henrique e Juliano"
}