### Cadastro
POST http://localhost:3003/user/signup 
Content-Type: application/json

{
   "name":"Felipe", 
   "email":"felipe@gmail.com", 
   "password":"1234567", 
   "role":"ADMIN"
}


### Login
POST http://localhost:3003/user/login 
Content-Type: application/json

{
   "email": "dickson@gmail.com", 
   "password":"12345678"
}

###  Registrar banda
POST http://localhost:3003/band/add 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3YzM2OWFlLTI5MDUtNGI4Zi1hNWQzLTczMDE3NjM1ODhkZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2OTQyMDgyMSwiZXhwIjoxNjY5NDIxNDIxfQ.WCotrUkgiK_BkbxitRhvqZisfSLT3eFcLtu9s_ng4zY
Content-Type: application/json

{
   "name": "Matanza", 
   "music_genre": "Rock", 
   "responsible": "Jimmy"
}


### DETALHES DAS BANDAS
GET http://localhost:3003/band/details/28b90bd2-c9f9-4842-b80f-9868f3b0c358

###BUSCAR BANDA PELO DIA E ORDENAR
GET http://localhost:3003/band/details/search?domingo



###BUSCAR BANDA PELO DIA E ORDENAR
GET http://localhost:3003/band/details/search?day="DOMINGO"

### ADICIONAR LISTA DE SHOWS
POST http://localhost:3003/band/added/4583b5b7-f1d1-41dc-8c0f-5b634275201c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU4ZTQzMDEyLWRlZGItNGQ0Ni05YjNjLTRhMDMzZjlhMTIzNyIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2OTMzODQ4OSwiZXhwIjoxNjY5MzM5MDg5fQ.wrLdldAHqRbK06e4axKnqzI-22lH3NUQ1eJ7zN1hT6w
Content-Type: application/json

{
   "weekDay" : "SEXTA",
    "startTime" : 12,
    "endTime" : 13
}

### ADICIONAR INGRESSOS
POST http://localhost:3003/band/ticket/d6b7b601-41c9-475b-b851-59eb53ada29a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg3YzM2OWFlLTI5MDUtNGI4Zi1hNWQzLTczMDE3NjM1ODhkZSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2OTQyMDkyMiwiZXhwIjoxNjY5NDIxNTIyfQ.aAX9nG94pN0gIA3zEWB09fcqDc2ngN1kiT7E4hooC9o
Content-Type: application/json

{
   "name" : "O ultimo show do ano",
    "value" : 200,
    "quantity" : 400
}